name: linux

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Build
        run: |
          cmake -B build -GNinja
          cmake --build build --config Release
          cmake --install build --prefix build/install

      - name: Compress Install Directory
        run: zip -r build/plasma_linux_x86-64_release.zip build/install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plasma_linux_x86-64_release
          path: build/plasma_linux_x86-64_release.zip
