name: macos

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew update
          brew install ninja

      - name: Build
        run: |
          cmake -B build -GNinja
          cmake --build build --config Release
          cmake --install build --prefix build/install

      - name: Compress Install Directory
        run: tar -czvf build/plasma_macos_arm64_release.tar.gz -C build/install .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plasma_macos_arm64_release
          path: build/plasma_macos_arm64_release.tar.gz
