name: xcframework

on:
  workflow_call:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        run: |
          cmake -B build/macos -G Xcode -DCMAKE_TOOLCHAIN_FILE=cmake/ios-cmake/ios.toolchain.cmake -DPLATFORM=MAC_UNIVERSAL -DBUILD_BINS=OFF -DYAML_SUPPORT=ON
          cmake --build build/macos --config Release
          cmake --install build/macos  --prefix build/install/macos

          cmake -B build/ios -G Xcode -DCMAKE_TOOLCHAIN_FILE=cmake/ios-cmake/ios.toolchain.cmake -DPLATFORM=OS64 -DBUILD_BINS=OFF -DYAML_SUPPORT=OFF
          cmake --build build/ios --config Release
          cmake --install build/ios  --prefix build/install/ios

          cmake -B build/ios-sim -G Xcode -DCMAKE_TOOLCHAIN_FILE=cmake/ios-cmake/ios.toolchain.cmake -DPLATFORM=SIMULATORARM64 -DBUILD_BINS=OFF -DYAML_SUPPORT=OFF
          cmake --build build/ios-sim --config Release
          cmake --install build/ios-sim --prefix build/install/ios-sim

          mkdir -p build/install/xcframework
          xcodebuild -create-xcframework \
              -library build/install/macos/lib/libplasma.a -headers build/install/macos/include \
              -library build/install/ios/lib/libplasma.a -headers build/install/ios/include \
              -library build/install/ios-sim/lib/libplasma.a -headers build/install/ios-sim/include \
              -output build/install/xcframework/plasma.xcframework

      - name: Compress Install Directory
        run: tar -czvf build/plasma_xcframework_release.tar.gz -C build/install/xcframework .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plasma_xcframework_release
          path: build/plasma_xcframework_release.tar.gz
